config/routes.rb
Rails.application.routes.draw do
  get 'artisans/edit'
  get 'artisans/update'
  get 'artisans/create'
	get '/', to: 'items#index', as: 'root'
  	devise_for :artisans
	resources :artisans, only: [:edit, :show, :update]
#	get '/artisans/sign_up/:id', to: '/artisans/sign_up'
	resources :carts, only: [:edit, :update]
	resources :orders, only: [:create, :show]
	resources :items, only: [:index, :show]
	resources :cart_items, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artisan.rb
class Artisan < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable
	has_many :orders
	has_one :cart
	# validates :first_name, :presence => true
	# validates :last_name, :presence => true
	validates :email, :presence => true, :uniqueness => true
	validates_format_of :email,:with => Devise::email_regexp
	validates :password, :presence => true, :length => { :minimum => 6, :message => "please, use minimum 6 characters" }

	# Following lines enable to send a welcome email to any new subscriber 
	after_create_commit	:send_welcome_mail
	def send_welcome_mail
    	new_email = Artisan.last.email
	    Mailing.new.new_subscriber(new_email)
    	# EmailSender.send_welcome_mail(email: email)
	end

end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	belongs_to :artisan, optional: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item 
	belongs_to :cart 
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :cart_items
	has_many :order_items
	validates :title, :presence => true
	validates :description, :presence => true
	validates :image_url, :presence => true
	validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :artisan
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_artisan!
  	include CartsHelper

  	def destroy
  		super
  		current_cart
  	end

end

app/controllers/artisans_controller.rb
class ArtisansController < ApplicationController
	skip_before_action :authenticate_artisan!, only: [:new, :index]

  def new
  end	

  def show
  end

  def edit
  end

  def update
  end

  def create
  	puts new_email = params['artisan']['email']
    Mailing.new.new_subscriber(new_email)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create

    item = Item.find(params['selected_item'])

  	#Création du premer cart_item
    add_to_cart = CartItem.new( 
      cart_id: current_cart.id,
      item_id: item.id,
      quantity: params['quantity'],
      price: item.price
    )
    add_to_cart.save

  	redirect_back fallback_location: edit_cart_path(current_cart.id)

  end

  def update

    puts current_cart.id
    cart_item = CartItem.find_by(cart_id: current_cart.id, item_id: params[:selected_item])
    if cart_item == nil
      create
    end

    #Actualisation de la quantité
    cart_item.quantity += params['quantity'].to_i

    #Cas d'une quantité de base =1
    if cart_item.quantity == 0
      cart_item.destroy
      #Cas de réduction du dernier item à une quantité 0
      if current_cart_items.count == 0
        redirect_to root_path and return
        #ajouter un message flash après la redirection
      end
    end

    cart_item.save

    current_cart.status = 'updated'
    current_cart.save

    redirect_back fallback_location: root_path
  end

  def destroy
    CartItem.find(params['id']).destroy
    redirect_back fallback_location: root_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
  end

  def edit
    @cart = Cart.find(params[:id])
  	@cart_amount = cart_price(@cart.id)
  	@items = @cart.cart_items.order(:id)
    
    #Statut modifié
    if @cart.status = 'created'
      @cart.status = 'displayed'
      @cart.save
    end

  end

  def update

  end



 private 
  
  def cart_price(id)
    total_price = 0
    CartItem.where(cart_id: id).each { |item|
      total_price += item.quantity * item.price 
    }
    return total_price
  end

end

app/controllers/items_controller.rb
include CartsHelper

class ItemsController < ApplicationController
  
	skip_before_action :authenticate_artisan!, only: [:index, :show]

  def index
  	current_cart
  	current_cart_items
  	puts 'debut'
  	puts current_cart.id
  	puts current_cart_items
  	puts 'fin'
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
  end

  def create

 	# Création de l'order
  	order = Order.create(
  		delivery_address: params['address'],
  		artisan: current_cart.artisan
  		)

  	# Création des items dans la table order_items
  	current_cart_items.each { |item|
  		create_order_item(item,order)
  	}
  	#Vidange du panier
  	empty_cart(current_cart)

    #Envoi email confirmation : récupère email puis active le mailing.rb
    buyer_email = Artisan.find(Order.last.artisan_id).email
    Mailing.new.new_buyer(buyer_email)

  	redirect_to order_path(order.id)

  end

  def show
  	@order = Order.find(params[:id])
  end
  
  private 

	def empty_cart(cart)
		cart.cart_items.destroy_all
	end

	def create_order_item(item, order)
		OrderItem.create(
  			quantity: item.quantity,
  			item_id: item.id,
  			price: item.price, 
  			order_id: order.id
  			)
	end 
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

   # DELETE /resource/sign_out
   def destroy

   end

   def create
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  	include CartsHelper
  	include Devise::Controllers::Helpers 
  	include OrderHelper

end

app/helpers/artisans_helper.rb
module ArtisansHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/carts_helper.rb
module CartsHelper


	def current_cart
		if artisan_signed_in? && Cart.find_by(artisan_id:current_artisan.id) != nil
			return Cart.find_by(artisan_id:current_artisan.id)
		elsif artisan_signed_in? && Cart.find_by(artisan_id:current_artisan.id) == nil
			new_cart = Cart.create(
					artisan_id: current_artisan.id,
			      	status: 'created'
					)
			return new_cart
		else
			if Cart.find_by(status:'default') == nil
				cart = Cart.create!(status:'default')
				return cart
			else
				return Cart.find_by(status:'default')
			end
		end
	end

	def current_cart_items
		if artisan_signed_in?
			current_cart.cart_items
		else
			{}
		end
	end

	def show_current_cart
		if artisan_signed_in?
			current_cart_items.each {|item|
				puts Item.find(item.item_id).title
			}
		else 
			return ['']
		end
	end


	def current_cart_price
		if artisan_signed_in?
		    total_price = 0
		    current_cart_items.each { |item|
		      total_price += item.quantity * item.price 
		    }
		    return total_price
		else 
			return 0
		end
	end

	def current_cart_count
		if artisan_signed_in?
		    total_count = 0
		    current_cart_items.each { |item|
		      total_count += item.quantity
		    }
		    return total_count
		else
			return 0
		end
	end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
	def order_count_items(id)
		total = 0
		Order.find(id).order_items.each do |order_item|
			total += order_item.quantity
		end
		return total	
	end
end

app/views/artisans/edit.html.erb
<div class= 'personal_info'> 
      <h3 class="title">Modify Account info</h3>
       <form>
          <div class="form-group">
            <label>Email address</label>
            <input type="email" class="form-control" value="<%= current_artisan.email %>">
          </div>
          <div class="form-group">
            <label> NewPassword</label>
            <input type="password" class="form-control" placeholder="Password">
          </div>   
          <div class="form-group">
            <label> Confirm your password</label>
            <input type="password" class="form-control" placeholder="Password">
          </div>                                      
          <%= link_to 'Save Edit', edit_artisan_path, :class => "btn btn-default" %> 
          <%= link_to 'Back to profil', artisan_path, :class => "btn btn-default" %>           
        </form>       
    </div>



<div class= 'shipping_info'> 
  <h3 class="title">Modify Shipping Info</h3>
   <form>
      <div class="form-group">
        <label>Phone</label>
        <input type="email" class="form-control" value="<%= current_artisan.email %>">
      </div>
      <div class="form-group">
        <label> Adress</label>
        <input type="password" class="form-control" placeholder="Password">
      </div>
      <div class="form-group">
        <label>City</label>
        <input type="email" class="form-control" value="<%= current_artisan.email %>">
      </div>
      <div class="form-group">
        <label> Postal code</label>
        <input type="password" class="form-control" placeholder="Password">
      </div>
     
      <%= link_to 'Save Edit', edit_artisan_path, :class => "btn btn-default" %> 
      <%= link_to 'Back to profil', artisan_path, :class => "btn btn-default" %>    
    </form>       
</div>

        <div class='shipping_info'> 
            <h3 class="title">My orders</h3>
            <div class="separator-2"></div>

            <% if current_artisan.orders.count > 0 %>
              <% render 'order/index' %>
            <% else %>
              <h4 class='text-center'>You have no past order</h4>
            <% end %> 
          </div>

app/views/cart_item/_edit.html.erb
<div>
	<h5><%= Item.find(cart_item.item_id).title %></h5>
	<p><%= cart_item.quantity %> </p>
	<p> <%= cart_item.quantity * cart_item.price %> €</p>
</div>

app/views/carts/_show.html.erb
  <div class="container_cart">
    <div class="row">     
      <div class="main col-12">      
        <h1 class="page-title">Shopping Cart</h1>
        <div class="separator-2"></div>
        <table class="table cart table-hover table-colored">
          <thead>
            <tr>
              <th></th>
              <th>Quantity</th>
              <th>Product</th>
              <th>Unit Price</th>
              <th class="amount">SubTotal</th>
              <th>Remove</th>

            </tr>
          </thead>
            <tbody>                
            <% @items.each do |cart_item| %>
           <tr>
            <td>
              <div class="col-6 align-center">
                  <%= link_to item_path(Item.find(cart_item.item_id)) do %> <%= image_tag Item.find(cart_item.item_id).image_url %> <% end %>
              </div>
            </td>
             <td> 

              <div class="quantity_row "> 
              <%= link_to cart_item_path(cart_item.id,quantity:'-1'), method: 'patch' do %>          
               <i class="fa fa-minus"></i>

              <% end %>
              <%= cart_item.quantity %>
              <%= link_to cart_item_path(cart_item.id,quantity:'1'), method: 'patch'  do %>
                <i class="fa fa-plus"></i>
              <% end %>
             </div>
            </td>
            <td class ="product">
             <%= link_to item_path(Item.find(cart_item.item_id)) do %> <h5><%= Item.find(cart_item.item_id).title %></h5><% end %>
           </td>
           <td class ="price"> <%= cart_item.price %> €</td>
        <td class="amount"><%= cart_item.quantity * cart_item.price %> €</td>
        <td>
          <%= link_to cart_item_path(cart_item.id), method: :delete, data: { confirm: 'Are you certain you want to remove this article?'} do %>
          <button class='btn btn-sm btn-danger'><i class="fa fa-trash"></i></button>
          <% end %>
        </td>
      </tr>
      <% end %>
      <tr>
        <td class="total-quantity text-right" colspan="3">Total <%= current_cart_count %> Items</td>
        <td class="total-amount"> <%= current_cart_price %> €</td>
      </tr>
    </tbody>

    <tfooter>
      <td class="total-quantity text-right" colspan="12">
        <%= link_to orders_path, method: :post, return:true do %>
        <button class='btn btn-success'><i class="fa fa-check"></i> Confirm cart</button>
        <% end %>
      </td>
    </tfooter>
  </table>
    </div>	
  </div>
</div>



 

app/views/carts/edit.html.erb
<div class="breadcrumb-container">
  <div class="container">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to root_path, class:"link-dark" do %><i class="fa fa-home pr-2"></i><% end %></li>
      <li class="breadcrumb-item active"><%= link_to 'My Cart', edit_cart_path(current_cart.id) %></li>
    </ol>
  </div>
</div>

<div class="main-container">


	<% if current_cart_count == 0 %>
		<h2>Votre panier est vide</h2>
	<% else %>
	<%= render "show" %>
  <div id="shipping">
    <%= render "shipping" %>
  </div>
  <div id="payment">
  	<%= render "payment" %>

  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<!-- scrollToTop -->
    <!-- ================ -->
    <div class="scrollToTop circle"><i class="fa fa-angle-up"></i></div>

    <!-- page wrapper start -->
    <!-- ================ -->
    <div class="page-wrapper">
      

      <div id="page-start"></div>

      <!-- section start -->
      <!-- ================ -->
      <section class="section light-gray-bg clearfix">
        <div class="container">
          <div class="row">
            <div class="col-md-12"> 
              <!-- Tab panes -->
              <div class="tab-content clear-style">
                <div class="tab-pane active" id="pill-1">
                  <div class="row grid-space-10">
                  <% Item.all.each do |item| %>
                    <div class="col-lg-3 col-md-6">
                      <div class="listing-item white-bg bordered mb-20">
                        <div class="overlay-container">
                          <div class="image_item_container">
                            <%= image_tag item.image_url, class:'image_item' %>
                          </div>
                            <%= link_to item_path(item.id), class:"overlay-link" do %>
                    
                          <% end %>
                        </div>
                        <div class="body">
                          <h3><%= link_to item.title, item_path(item.id) %></h3>
                          <p class="small"><%= item.description %></p>
                          <div class="elements-list clearfix">
                            <span class="price"><%= item.price %> €</span>

                            <% begin %>
                              <%= form_tag(cart_item_path(CartItem.find_by(cart_id: current_cart.id, item_id: item.id).id), method: "patch") do %>
                                <%= hidden_field_tag 'selected_item', item.id %>
                                <%= hidden_field_tag 'quantity', 1 %>
                                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                                <%= button_tag(type: "submit", class: "pull-right margin-clear btn btn-sm btn-default-transparent btn-animated") do%>
                                  Add To Cart<i class="fa fa-shopping-cart"></i>
                                <% end %>
                              <% end %>
                            <% rescue %>
                              <%= form_tag(cart_items_path, method: "create") do %>
                                <%= hidden_field_tag 'selected_item', item.id %>
                                <%= hidden_field_tag 'quantity', 1 %>
                                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                                <%= button_tag(type: "submit", class: "pull-right margin-clear btn btn-sm btn-default-transparent btn-animated") do%>
                                  Add To Cart<i class="fa fa-shopping-cart"></i>
                                <% end %>
                              <% end %>
                            <% end %>

<!--                            <a href="#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a> -->

                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  </div>
                </div>
              </div>
              <!-- pills end -->
            </div>
          </div>
        </div>
      </section>
      <!-- section end -->
    </div>
    <!-- page-wrapper end -->

app/views/items/show.html.erb
<!-- scrollToTop -->
    <!-- ================ -->
    <div class="scrollToTop circle"><i class="fa fa-angle-up"></i></div>

    <!-- page wrapper start -->
    <!-- ================ -->
    <div class="page-wrapper">
      <!-- breadcrumb start -->
      <!-- ================ -->
      <div class="breadcrumb-container">
        <div class="container">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to root_path, class:"link-dark" do %><i class="fa fa-home pr-2"></i><% end %></li>
            <li class="breadcrumb-item active"><%= link_to @item.title, item_path(@item.id) %></li>
          </ol>
        </div>
      </div>
      <!-- breadcrumb end -->

      <!-- main-container start -->
      <!-- ================ -->
      <section class="main-container">

        <div class="container">
          <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-12">

              <!-- page-title start -->
              <!-- ================ -->
              <div class='row'> 
                <h1 class="page-title mr-auto"><%= @item.title %></h1>
              </div>

              <div class="separator-2"></div>
              <!-- page-title end -->

              <div class="row">
                <div class="col-lg-6">
                
                  <%= image_tag @item.image_url %>
                  
                </div>
                <div class="col-lg-6">
                  <div class= 'row mt-4'>
                    <h2 class='mr-auto'>Description</h2>
                    <div class="product price"> <%= @item.price %> €</div>
                  </div>

                  <p><%= @item.description %></p>
                  <hr class="mb-10">


                    <% begin %>
                      <%= form_tag(cart_item_path(CartItem.find_by(cart_id: current_cart.id, item_id: params[:id]).id), method: "patch") do %>
                      <div class ='row align-items-center'>
                          <span>Quantity</span> <%= text_field_tag 'quantity','1', class:"form-group mb-0 col-lg-1 form-control ml-2 pl-2 mr-auto" %>
                          <%= hidden_field_tag 'selected_item', @item.id %>
                          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                          <%= button_tag(type: "submit", class: "pull-right margin-clear btn btn-default-transparent btn-animated") do%>
                            Add To Cart<i class="fa fa-shopping-cart"></i>
                          </div>
                          <% end %> 
                        <% end %>
                    <% rescue %>
                      <%= form_tag(cart_items_path, method: "create") do %>
                       <div class ='row_description'> 
                          Quantity <%= text_field_tag 'quantity', '1', class:"form-group mb-0 col-lg-1 form-control ml-2 pl-2 mr-auto" %>
                          <%= hidden_field_tag 'selected_item', @item.id %>
                          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                          <%= button_tag(type: "submit", class: "pull-right margin-clear btn btn-default-transparent btn-animated") do%>
                            Add To Cart<i class="fa fa-shopping-cart"></i>
                          </div>
                          <% end %> 
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- main end -->

          </div>
        </div>
      </section>
      <!-- main-container end -->
    </div>
    <!-- page-wrapper end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpWeek9Catposters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Web Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- header-container start -->
      <div class="header-container">
        <!-- header start -->
        <!-- classes:  -->
        <!-- "fixed": enables fixed navigation mode (sticky menu) e.g. class="header fixed clearfix" -->
        <!-- "fixed-desktop": enables fixed navigation only for desktop devices e.g. class="header fixed fixed-desktop clearfix" -->
        <!-- "fixed-all": enables fixed navigation only for all devices desktop and mobile e.g. class="header fixed fixed-desktop clearfix" -->
        <!-- "dark": dark version of header e.g. class="header dark clearfix" -->
        <!-- "centered": mandatory class for the centered logo layout -->
        <!-- ================ -->
        <header class="header fixed fixed-desktop clearfix">
          <div class="container-fluid">
            <div class="row">

              <div class="col-md-auto hidden-md-down pl-3">
                <!-- header-first start -->
                <!-- ================ -->
                <div class="header-first clearfix">
                  <!-- logo -->
                  <div id="logo" class="logo">
                    <%= link_to root_path do %>
                      <img id="logo_img" src="../../assets/images/kraft.png" alt="kraft">
                    <% end %>
                  </div>
                </div>
                <!-- header-first end -->
              </div>


              <div class="col-lg-8 ml-auto">
          
                <!-- header-second start -->
                <!-- ================ -->
                <div class="header-second clearfix">
                  
                <!-- main-navigation start -->
                <!-- classes: -->
                <!-- "onclick": Makes the dropdowns open on click, this the default bootstrap behavior e.g. class="main-navigation onclick" -->
                <!-- "animated": Enables animations on dropdowns opening e.g. class="main-navigation animated" -->
                <!-- ================ -->
                <div class="main-navigation main-navigation--mega-menu  animated">
                  <nav class="navbar navbar-expand-lg navbar-light p-0">


                    <div class="navbar-brand clearfix hidden-lg-up">
                      <!-- logo -->
                      <div id="logo-mobile" class="logo">
                        <%= link_to root_path do %>
                          <img id="logo_img" src="../../assets/images/kraft.png" alt="kraft">
                        <% end %>
                      </div>
                    </div>
                    
                    <!-- header dropdown buttons -->
                    <div class="header-dropdown-buttons hidden-lg-up p-0 ml-auto mr-3">


                      <div class="btn-group">
                        <button type="button" class="btn dropdown-toggle dropdown-toggle--no-caret" id="header-drop-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-animation" aria-labelledby="header-drop-3">
                          <% unless artisan_signed_in? %>
                          <li><%= link_to 'Login', new_artisan_session_path, class: "nav-link" %></li>
                          <li><%= link_to 'Signup', new_artisan_registration_path, class: "nav-link" %></li>
                          <% else %>
                          <li><%= link_to 'My profile', artisan_path(current_artisan.id), class: "nav-link"%></li>
                          <li><%= link_to 'Logout', destroy_artisan_session_path, class: "nav-link", method: :delete %></li>
                          <% end %>
                        </ul>
                      </div>


                      <div class="btn-group">
                        <button type="button" class="btn dropdown-toggle dropdown-toggle--no-caret" id="header-drop-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-shopping-basket"></i><span class="cart-count default-bg"><%= current_cart_count %></span></button>
                        <ul class="dropdown-menu dropdown-menu-right cart dropdown-animation" aria-labelledby="header-drop-4">
                          <li>
                            <table class="table table-hover">
                              <thead>
                                <tr>
                                  <th class="quantity">Qty</th>
                                  <th class="product">Product</th>
                                  <th class="amount">Subtotal</th>
                                </tr>
                              </thead>
                              <tbody>
                                <% unless current_cart_count == 0 %>
                                  <% current_cart_items.each do |item| %>
                                  <tr>
                                    <td class="quantity"> <%= item.quantity %> </td>
                                    <td class="product"><a href="shop-product.html"><%= Item.find(item.item_id).title %></a></td>
                                    <td class="amount"><%= item.price * item.quantity %> €</td>
                                  </tr>
                                  <% end %>
                                <% end %> 
                                <tr>
                                  <td class="total-quantity" colspan="2">Total <%= current_cart_count %> Items</td>
                                  <td class="total-amount"><%= current_cart_price %> €</td>
                                </tr>
                              </tbody>
                            </table>
                            <div class="panel-body text-right">
                              <%= link_to 'Checkout', edit_cart_path(current_cart.id), class:"btn btn-outline-info btn-sm" %>
                            </div>
                          </li>
                        </ul>
                      </div>

                    </div>
                  </nav>
                </div>
                <!-- main-navigation end -->
                </div>
                <!-- header-second end -->
              </div>



              <div class="col-auto hidden-md-down row">
                <!-- header dropdown buttons -->

                <% unless artisan_signed_in? %>

                  <nav class="navbar navbar-expand-lg navbar-light p-0 ">
                    <ul class="navbar-nav ml-xl-auto">
                      <li><%= link_to 'Login', new_artisan_session_path, class: "nav-link" %></li>
                      <li><%= link_to 'Signup', new_artisan_registration_path, class: "nav-link" %></li>
                    </ul>
                  </nav>

                <% else %>

                <div class="header-dropdown-buttons">
                   <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle dropdown-toggle--no-caret" id="header-drop-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i></button>
                    <ul class="dropdown-menu dropdown-menu-right dropdown-animation" aria-labelledby="header-drop-3">
                      <li><%= link_to 'My profile', artisan_path(current_artisan.id), class: "nav-link"%></li>
                      <li><%= link_to 'Logout', destroy_artisan_session_path, class: "nav-link", method: :delete %></li>
                    </ul> 
                  </div>
                </div>
                <% end %>

                <div class="header-dropdown-buttons">
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle dropdown-toggle--no-caret" id="header-drop-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-shopping-basket"></i><span class="cart-count default-bg"><%= current_cart_count %></span></button>
                    <ul class="dropdown-menu dropdown-menu-right cart dropdown-animation" aria-labelledby="header-drop-4">
                      <li>
                        <table class="table table-hover">
                          <thead>
                            <tr>
                              <th class="quantity">Qty</th>
                              <th class="product">Product</th>
                              <th class="amount">Subtotal</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% unless current_cart_count == 0 %>
                              <% current_cart_items.each do |item| %>
                              <tr>
                                <td class="quantity"> <%= item.quantity %> </td>
                                <td class="product"><%= link_to Item.find(item.item_id).title, item_path(item.item_id) %></a></td>
                                <td class="amount"><%= item.price * item.quantity %> €</td>
                              </tr>
                              <% end %>
                            <% end %>
                            <tr>
                              <td class="total-quantity" colspan="2">Total <%= current_cart_count %> Items</td>
                              <td class="total-amount"><%= current_cart_price %> €</td>
                            </tr>
                          </tbody>
                        </table>
                        <div class="panel-body text-right">
                          <%= link_to 'Checkout', edit_cart_path(current_cart.id), class:"btn btn-outline-info btn-sm" %>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>

              </div>


                <!-- header dropdown buttons end -->
              </div>
            </div>
          </div>
        </header>
        <!-- header end -->
      </div>
<!-- header-container end -->